import { PgPromiseAdapter } from "./infra/database/DatabaseConnection";
import { ExpressAdapter } from "./infra/http/HttpServer";
import Registry from "./infra/di/Registry";
import { WalletRepositoryDatabase } from "./infra/repository/WalletRepository";
import OrderController from "./infra/controller/OrderController";
import { OrderRepositoryDatabase } from "./infra/repository/OrderRepository";
import FillOrder from "./application/usecase/FillOrder";
import Deposit from "./application/usecase/Deposit";
import PlaceOrder from "./application/usecase/PlaceOrder";
import Mediator from "./infra/mediator/Mediator";
import ExecuteOrder from "./application/usecase/ExecuteOrder";
import { BookGatewayHttp } from "./infra/gateway/BookGateway";
import { RabbitMQAdapter, RabbitMQOutboxAdapter } from "./infra/queue/Queue";
import GetOrder from "./application/usecase/GetOrder";
import { AccountGatewayHttp } from "./infra/gateway/AccountGateway";
import GetOrders from "./application/usecase/GetOrders";
import { OrderDAODatabase } from "./infra/dao/OrderDAO";
import CreateOrderProjection from "./application/usecase/CreateOrderProjection";
import UpdateOrderProjection from "./application/usecase/UpdateOrderProjection";

async function main () {
    const httpServer = new ExpressAdapter();
    const queue = new RabbitMQAdapter();
    // const queue = new RabbitMQOutboxAdapter();
    await queue.connect();
    await queue.setup("orderPlaced", "orderPlaced.executeOrder");
    await queue.setup("orderPlaced", "orderPlaced.createOrderProjection");
    await queue.setup("orderFilled", "orderFilled.fillOrder");
    await queue.setup("orderFilled", "orderFilled.updateOrderProjection");
    await queue.setup("placeOrder", "placeOrder.placeOrder");
    Registry.getInstance().register("httpServer", httpServer);
    Registry.getInstance().register("queue", queue);
    Registry.getInstance().register("databaseConnection", new PgPromiseAdapter());
    Registry.getInstance().register("orderRepository", new OrderRepositoryDatabase());
    Registry.getInstance().register("orderDAO", new OrderDAODatabase());
    Registry.getInstance().register("walletRepository", new WalletRepositoryDatabase());
    Registry.getInstance().register("accountGateway", new AccountGatewayHttp());
    Registry.getInstance().register("bookGateway", new BookGatewayHttp());
    Registry.getInstance().register("mediator", new Mediator());
    Registry.getInstance().register("placeOrder", new PlaceOrder());
    Registry.getInstance().register("deposit", new Deposit());
    Registry.getInstance().register("fillOrder", new FillOrder());
    Registry.getInstance().register("executeOrder", new ExecuteOrder());
    Registry.getInstance().register("getOrder", new GetOrder());
    Registry.getInstance().register("getOrders", new GetOrders());
    Registry.getInstance().register("createOrderProjection", new CreateOrderProjection());
    Registry.getInstance().register("updateOrderProjection", new UpdateOrderProjection());
    new OrderController();
    httpServer.listen(3000);
}

main();
